---
- name: Create bootstrap-osd and osd directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ 'ceph' }}"
    group: "{{ 'ceph' }}"
    mode: "{{ ceph_directories_mode }}"
  with_items:
    - /var/lib/ceph/bootstrap-osd/
    - /var/lib/ceph/osd/

- name: Get keys from monitors
  ceph_key:
    name: "{{ item.name }}"
    cluster: "{{ cluster }}"
    output_format: plain
    state: info
  register: _osd_keys
  with_items:
    - { name: "client.bootstrap-osd", path: "/var/lib/ceph/bootstrap-osd/{{ cluster }}.keyring", copy_key: true }
    - { name: "client.admin", path: "/etc/ceph/{{ cluster }}.client.admin.keyring", copy_key: "{{ copy_admin_key }}" }
  delegate_to: "{{ groups.get(mon_group_name)[0] }}"
  run_once: true
  no_log: "{{ no_log_on_ceph_key_tasks }}"
  when:
    - item.copy_key | bool

- name: Copy ceph key(s) if needed
  ansible.builtin.copy:
    dest: "{{ item.item.path }}"
    content: "{{ item.stdout + '\n' }}"
    owner: "{{ ceph_uid if containerized_deployment | bool else 'ceph' }}"
    group: "{{ ceph_uid if containerized_deployment | bool else 'ceph' }}"
    mode: "{{ ceph_keyring_permissions }}"
  with_items: "{{ _osd_keys.results }}"
  when:
    - item is not skipped
    - item.item.copy_key | bool
  no_log: "{{ no_log_on_ceph_key_tasks }}"
