---
- name: Set_fact vm_min_free_kbytes
  ansible.builtin.set_fact:
    vm_min_free_kbytes: "{{ 4194303 }}"

- name: Apply operating system tuning
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/ceph-tuning.conf
    sysctl_set: true
    ignoreerrors: true
  with_items:
    - { name: "fs.aio-max-nr", value: "1048576", enable: "{{ osd_objectstore == 'bluestore' }}" }
    - "{{ os_tuning_params }}"
  when: item.enable | default(true) | bool
