---
- name: Use ceph-volume to create osds
  ceph_volume:
    cluster: "{{ cluster }}"
    objectstore: "{{ osd_objectstore }}"
    data: "{{ item.data }}"
    data_vg: "{{ item.data_vg | default(omit) }}"
    db: "{{ item.db | default(omit) }}"
    db_vg: "{{ item.db_vg | default(omit) }}"
    wal: "{{ item.wal | default(omit) }}"
    wal_vg: "{{ item.wal_vg | default(omit) }}"
    crush_device_class: "{{ item.crush_device_class | default(crush_device_class) | default(omit) }}"
    dmcrypt: "{{ dmcrypt | default(omit) }}"
    action: "{{ 'create' }}"
  with_items: "{{ lvm_volumes }}"
  tags: prepare_osd
