---
- name: Install ceph mds for debian
  ansible.builtin.apt:
    name: ceph-mds
    state: "{{ (upgrade_ceph_packages | bool) | ternary('latest', 'present') }}"
    default_release: "{{ ceph_stable_release_uca | default('') if ceph_origin == 'repository' and ceph_repository == 'uca' else '' }}{{ ansible_facts['distribution_release'] ~ '-backports' if ceph_origin == 'distro' and ceph_use_distro_backports | bool else '' }}"
  when:
    - mds_group_name in group_names
    - ansible_facts['os_family'] == 'Debian'
  register: result
  until: result is succeeded

- name: Install ceph-mds package on redhat or SUSE/openSUSE
  ansible.builtin.package:
    name: "ceph-mds"
    state: "{{ (upgrade_ceph_packages | bool) | ternary('latest', 'present') }}"
  register: result
  until: result is succeeded
  when:
    - mds_group_name in group_names
    - ansible_facts['os_family'] in ['Suse', 'RedHat']

- name: Start and add that the metadata service to the init sequence
  ansible.builtin.systemd:
    name: ceph-mds@{{ ansible_facts['hostname'] }}
    state: started
    enabled: true
    masked: false
  changed_when: false
